### ISSUE TITLE
AuditorPraise - BBLeverage.buyCollateral() and BBLendingCommon._repay() will have issues withdrawing from yieldBox for `from`

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-02-tapioca-judging#16]
AuditorPraise

high

# BBLeverage.buyCollateral() and BBLendingCommon._repay() will have issues withdrawing from yieldBox for `from`

## Summary
access control was implemented on yieldbox's withdraw() function
```solidity
 function withdraw(
        uint256 assetId,
        address from,
        address to,
        uint256 amount,
        uint256 share
    ) public allowed(from) returns (uint256 amountOut, uint256 shareOut) {
```
## Vulnerability Detail
 it seems withdrawals from the yieldbox will be impossible when your contracts try to withdraw for another person as there's some kind of access control implemented on it.

```solidity
/// Modifier to check if the msg.sender is allowed to use funds belonging to the 'from' address.
    /// If 'from' is msg.sender, it's allowed.
    /// If 'msg.sender' is an address (an operator) that is approved by 'from', it's allowed.
    modifier allowed(address from) {
        _requireTransferAllowed(from);
        _;
    }
```
The above modifier won't let `BBLendingCommon` and `BBLeverage` withdraw funds for `from` , if `from` doesn't set them as an operator for his account.

This also affects YieldBox.transfer() done in [`_addCollateral`](https://github.com/sherlock-audit/2024-02-tapioca/blob/main/Tapioca-bar/contracts/markets/origins/Origins.sol#L265) 

## Impact
withdrawals from the yieldbox will be impossible if `from` doesn't set `BBLendingCommon` and `BBLeverage` as operators for his account.

BBLeverage.buyCollateral() and BBLendingCommon._repay() will have issues withdrawing from yieldBox for `from`

Also YieldBox.transfer() done in Origins._addCollateral() will encounter similar problems if `from` doesn't set Origins.sol as an operator 
 for his account.
## Code Snippet

https://github.com/boringcrypto/YieldBox/blob/cd62ffc4b003e4de428b45169010e94b523caef4/contracts/YieldBox.sol#L206

https://github.com/boringcrypto/YieldBox/blob/cd62ffc4b003e4de428b45169010e94b523caef4/contracts/NativeTokenFactory.sol#L36-L42

https://github.com/sherlock-audit/2024-02-tapioca/blob/main/Tapioca-bar/contracts/markets/bigBang/BBLendingCommon.sol#L129

https://github.com/sherlock-audit/2024-02-tapioca/blob/main/Tapioca-bar/contracts/markets/bigBang/BBLeverage.sol#L78

## Tool used

Manual Review

## Recommendation
look for a way to have `from` approve `BBLendingCommon` and `BBLeverage` as operators for his account directly in the yieldBox from your codebase 

Duplicate of #138

**Comment by cryptotechmaker** [comment]
Invalid

**Comment by AuditorPraise** [comment]
> Invalid

Please take a second look at this issue, because i think it won't be an issue only if this isn't the yieldBox contract your contracts are interacting with - https://github.com/boringcrypto/YieldBox/blob/cd62ffc4b003e4de428b45169010e94b523caef4/contracts/YieldBox.sol

Yield Box's withdraw() function has `allowed` modifier on it -- https://github.com/boringcrypto/YieldBox/blob/cd62ffc4b003e4de428b45169010e94b523caef4/contracts/YieldBox.sol#L206
```solidity
 function withdraw(
        uint256 assetId,
        address from,
        address to,
        uint256 amount,
        uint256 share
    ) public allowed(from) returns (uint256 amountOut, uint256 shareOut) {
```

Here's the  Allowed` modifier --https://github.com/boringcrypto/YieldBox/blob/cd62ffc4b003e4de428b45169010e94b523caef4/contracts/NativeTokenFactory.sol#L36-L42
```solidity
   /// Modifier to check if the msg.sender is allowed to use funds belonging to the 'from' address.
    /// If 'from' is msg.sender, it's allowed.
    /// If 'msg.sender' is an address (an operator) that is approved by 'from', it's allowed.
    modifier allowed(address from) {
        _requireTransferAllowed(from);
        _;
    }
```
The  `_requireTransferAllowed(from);` will give issues because it checks and ensures that for the wihdrawal to succeed either `from` is the msg.sender or msg.sender is an approved operator for `from`
https://github.com/boringcrypto/YieldBox/blob/cd62ffc4b003e4de428b45169010e94b523caef4/contracts/ERC1155.sol#L95-L97
```solidity
    function _requireTransferAllowed(address from) internal view virtual {
        require(from == msg.sender || isApprovedForAll[from][msg.sender] == true, "Transfer not allowed");
    }
```
