### ISSUE TITLE
duc - Using wrong token for the approve action in the `buyCollateral` function

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-02-tapioca-judging#56]
duc

medium

# Using wrong token for the approve action in the `buyCollateral` function

## Summary
The `buyCollateral()` function in BBLeverage and SGLLeverage is used to borrow assets and swap to add collateral into the market. After collecting collateral tokens, it attempts to deposit collateral tokens into YieldBox to obtain YieldBox's shares of collateral, but incorrectly approves the asset token.
## Vulnerability Detail
`BBLeverage.buyCollateral()` approves the asset token for YieldBox but deposits the `collateralId` token for YieldBox.
```solidity=
address(asset).safeApprove(address(yieldBox), type(uint256).max);
yieldBox.depositAsset(collateralId, address(this), address(this), 0, collateralShare); // TODO Check for rounding attack?
address(asset).safeApprove(address(yieldBox), 0);
```
The same vulnerability exists in `SGLLeverage.buyCollateral()`.

## Impact
`buyCollateral` won't work because it will revert in YieldBox due to lacking allowance (broke core functionality).
## Code Snippet
https://github.com/sherlock-audit/2024-02-tapioca/blob/main/Tapioca-bar/contracts/markets/bigBang/BBLeverage.sol#L103-L105
https://github.com/sherlock-audit/2024-02-tapioca/blob/main/Tapioca-bar/contracts/markets/singularity/SGLLeverage.sol#L87-L89

## Tool used

Manual Review

## Recommendation
Should approve the collateral token.

Duplicate of #100

**Comment by huuducsc** [comment]
Escalate
I believe this issue is not a duplicate of #42 since this issue describes a different vulnerability in a different function. Regarding this issue, in the `buyCollateral` function, depositing collateral tokens into YieldBox is correct, but the approval is wrong since it approves asset tokens instead of collateral tokens for YieldBox. However, issue #42 represents a different situation where the function `sellCollateral` uses the wrong tokens for depositing. 
Additionally, the fix for #42 didn't address this issue, and this one hasn't been fixed yet.

**Comment by sherlock-admin2** [comment]
> Escalate
> I believe this issue is not a duplicate of #42 since this issue describes a different vulnerability in a different function. Regarding this issue, in the `buyCollateral` function, depositing collateral tokens into YieldBox is correct, but the approval is wrong since it approves asset tokens instead of collateral tokens for YieldBox. However, issue #42 represents a different situation where the function `sellCollateral` uses the wrong tokens for depositing. 
> Additionally, the fix for #42 didn't address this issue, and this one hasn't been fixed yet.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cvetanovv** [comment]
This issue is not a duplicate of #42 but is a duplicate of #100. 

#100 contains several problems of `buyCollateral()` function, and we can duplicate them.

**Comment by huuducsc** [comment]
I still don't see any reason why this issue should be marked as a duplicate of #100. The problem with this issue is that the `buyCollateral()` function uses the wrong token address for depositing, which is not related to any problem mentioned in #100. Here is the list of problems from #100:
<img width="804" alt="Screenshot 2024-04-07 at 06 42 00" src="https://github.com/sherlock-audit/2024-02-tapioca-judging/assets/80202717/1026b141-164f-4cd0-8aee-3a1e347b1f65">

Additionally, the fix for #100 doesn't address this issue, so I believe this issue should be considered separate it.

**Comment by cvetanovv** [comment]
Planning to accept the escalation as not dup of #42 and duplicate with #100.

**Comment by Evert0x** [comment]
Result:
Medium
Duplicate of #100

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [huuducsc](https://github.com/sherlock-audit/2024-02-tapioca-judging/issues/56/#issuecomment-2031966035): accepted
